spring:
  application:
    name: webgateway
  redis:
      host: 192.168.200.128
      port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
            - GET
            - POST
            - PUT
            - DELETE
      routes:
      - id: goods
        uri: lb://goods
        predicates:
        - Path=/goods/**
        filters:
        - StripPrefix= 1
        - name: RequestRateLimiter #请求数限流 名字不能随便写
          args:
            key-resolver: "#{@ipKeyResolver}"
            redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率
            redis-rate-limiter.burstCapacity: 1 #令牌桶总容量
        #用户微服务
      - id: user
        uri: lb://user
        predicates:
        - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
        filters:
        - StripPrefix=1
        #认证微服务
      - id: user-auth
        uri: lb://user-auth
        predicates:
        - Path=/api/oauth/**
        filters:
        - StripPrefix=1
        #订单微服务
      - id: order
        uri: lb://order
        predicates:
        - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
        filters:
        - StripPrefix=0
        #购物车订单渲染微服务
      - id: order_web
        uri: lb://order-web
        predicates:
        - Path=/api/wcart/**,/api/worder/**
        filters:
        - StripPrefix=1
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true